import Head from "next/head";
import styles from "@/styles/Home.module.css";
import {Box, Heading, Text} from "@chakra-ui/react"
import UseStateString from "./owie/useStateString";
import UseStateNumber from "./owie/UseStateNumber";
import UseStateBoolean from "./owie/UseStateBoolean";
import UseStateArray from "./owie/UseStateArray";
import UseStateTimer from "./owie/UseStateTimer";
import UseStateObject from "./owie/UseStateObject";
export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
        <main className={styles.main}>
        <Box m="10">
          <Heading>UseState and UseEffect Practice</Heading>
          <Text color="Red">String</Text>
          <UseStateString></UseStateString>
          <hr/>
          <Text color="Red">Number</Text>
          <UseStateNumber></UseStateNumber>
          <hr/>
          <Text color="Red">Boolean</Text>
          <UseStateBoolean></UseStateBoolean>
          <hr/>
          <Text color="Red">Array</Text>
          <UseStateArray></UseStateArray>
          <hr/>
          <Text color="Red">useEffect Timer</Text>
          <UseStateTimer></UseStateTimer>
          <hr/>
          <Text color="Red">useState Object</Text>
          <UseStateObject></UseStateObject>
        </Box>
        </main>
    </>
  );
}
